## Everforest Dark Hard theme for kitty
## Upstream: github.com/sainnhe/everforest

background            #1a2024
foreground            #d3c6aa
cursor                #d3c6aa
cursor_text_color     #272e33
url_color             #7fbbb3
selection_background  #425047
selection_foreground  #d3c6aa

# black
color0  #343f44
color8  #475258

# red
color1  #e67e80
color9  #e67e80

# green
color2  #a7c080
color10 #a7c080

# yellow
color3  #dbbc7f
color11 #dbbc7f

# blue
color4  #7fbbb3
color12 #7fbbb3

# magenta
color5  #d699b6
color13 #d699b6

# cyan
color6  #83c092
color14 #83c092

# white
color7  #859289
color15 #d3c6aa

# tabs
active_tab_foreground   #272e33
active_tab_background   #a7c080
inactive_tab_foreground #859289
inactive_tab_background #2e383c

# windows
active_border_color   #a7c080
inactive_border_color #343f44
